import HomeLayout from "./HomeLayout";
import HomePage from "./HomePage";
import Profile from "./Profile";
import Authorization from "./Authorization";
import Verification from "./Verification";
import ResetPassword from "./ResetPassword";
import Leaderboard from "./Leaderboard";
import AddQuestion from "./AddQuestion";
import About from "./About";
import AllQuestions from "./AllQuestions";
import ProtectedRoute from "./ProtectedRoute";
import QuizCategory from "./QuizCategory";
export {HomeLayout,HomePage,Profile,Authorization,Verification,ResetPassword,Leaderboard,AddQuestion,About,AllQuestions,ProtectedRoute,QuizCategory};